### ISSUE TITLE
Samples file missing

### ISSUE THREAD

**Issue by nkalvi** [shaps80/MarkdownTextDemo#1]
Please add the `Samples` file. Couldn't compile as the file is missing:

`../MarkdownView/Resources/Samples: No such file or directory`

**Comment by nkalvi** [comment]
Thanks.

But now I'm getting an error: `The data couldn’t be read because it isn’t in the correct format.` and the `Trending` list is empty.

**Comment by shaps80** [comment]
Hmm works for me, I just pulled `main` and ran (on macOS but still).

**Comment by nkalvi** [comment]
Thanks again. I think the problem is because I don't have access to the repo: 
`private static let url = URL(string: "https://gh-trending-api.herokuapp.com/repositories/swift")!`

When paste the url in a browser, I get this:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
> heroku logs --tail

I'll follow the docs in the original repo from now on.
